# Generated by Django 3.2.25 on 2025-03-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Salad', 'Salad'), ('Rolls', 'Rolls'), ('Deserts', 'Deserts'), ('Sandwich', 'Sandwich'), ('Cake', 'Cake'), ('Pure Veg', 'Pure Veg'), ('Pasta', 'Pasta'), ('Noodles', 'Noodles'), ('Biriyani', 'Biriyani'), ('Kacchi', 'Kacchi')], default='Salad', max_length=50),
        ),
    ]
